<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Web-QA-56" failures="1" tests="1" name="Banking_project_test" time="24.867" errors="0" timestamp="2022-05-23T17:00:14 IST">
  <testcase classname="banking.testCases.TC_DeleteCustomerTest_005" name="deleteCustomer" time="11.604">
    <failure type="java.lang.AssertionError" message="expected [Customer has been deleted successfully!!] but found [Customer does not exist!!]">
      <![CDATA[java.lang.AssertionError: expected [Customer has been deleted successfully!!] but found [Customer does not exist!!]
at banking.testCases.TC_DeleteCustomerTest_005.deleteCustomer(TC_DeleteCustomerTest_005.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteCustomer -->
</testsuite> <!-- Banking_project_test -->
